"""F5: derive Cedar policies deterministically from the frozen KB.

AgentCore Policy (GA March 3, 2026) stores Cedar policies in a policy
engine attached to an AgentCore Gateway; the gateway evaluates every
agent-to-tool request before allowing or denying it, independently of the
model. Entity model, from the AgentCore developer guide (example-policies,
policy-understanding-cedar):

    principal   AgentCore::OAuthUser | AgentCore::IamEntity (any principal here)
    action      AgentCore::Action::"<TargetName>___<tool_name>"
    resource    AgentCore::Gateway::"<gateway arn>"
    context     context.input.<tool parameter>

Semantics: default deny, forbid wins. The generated set says: a governed
tool may be called only with station abbreviations in the KB set, elevator
ids in the KB set, and option labels in BART's ranked set. Everything else
is denied, twice: no permit matches, and an explicit forbid matches.

Deterministic: stations and elevators sorted, options in BART's published
order, no timestamps, so regeneration from the same KB is byte-identical.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .interfaces import KBSet

ROOT = Path(__file__).resolve().parent.parent
POLICY_DIR = ROOT / "infra" / "agentcore" / "policy"
TOOLS_PATH = ROOT / "infra" / "agentcore" / "tools.json"
GATEWAY_ARN_PLACEHOLDER = "${GATEWAY_ARN}"

HEADER = (
    "// Generated by scripts/gen_cedar.py from the KB export (see manifest.json for the source tag).\n"
    "// Do not edit by hand. Regenerate with `make agentcore-policy-gen`.\n"
    "// Default deny, forbid wins: tools accept only KB stations, KB elevators, and BART's option labels.\n"
)


@dataclass
class GovernedTool:
    """A gateway tool and which of its parameters carry stations, elevators, options."""

    name: str
    station_params: list[str] = field(default_factory=list)
    elevator_params: list[str] = field(default_factory=list)
    option_params: list[str] = field(default_factory=list)


def load_tools(path: str | Path = TOOLS_PATH) -> tuple[str, list[GovernedTool]]:
    data = json.loads(Path(path).read_text())
    fields = GovernedTool.__dataclass_fields__
    tools = [GovernedTool(**{k: v for k, v in t.items() if k in fields}) for t in data["tools"]]
    return data["target_name"], tools


def cedar_set(values: list[str]) -> str:
    return "[" + ", ".join(f'"{v}"' for v in values) + "]"


def action(target: str, tool: str) -> str:
    return f'AgentCore::Action::"{target}___{tool}"'


def permit_policy(target: str, tool: GovernedTool, kb: KBSet, gateway_arn: str) -> str:
    conds = []
    st = cedar_set(sorted(kb.stations))
    ev = cedar_set(sorted(kb.elevators))
    op = cedar_set(list(kb.option_labels))
    for p in tool.station_params:
        conds.append(f"context.input has {p} && {st}.contains(context.input.{p})")
    for p in tool.elevator_params:
        conds.append(f"context.input has {p} && {ev}.contains(context.input.{p})")
    for p in tool.option_params:
        conds.append(f"context.input has {p} && {op}.contains(context.input.{p})")
    when = " &&\n  ".join(conds) if conds else "true"
    return (
        f"// {tool.name}: permitted only with KB stations, KB elevators, BART option labels\n"
        f"permit(\n  principal,\n  action == {action(target, tool.name)},\n"
        f'  resource == AgentCore::Gateway::"{gateway_arn}"\n)\nwhen {{\n  {when}\n}};\n'
    )


def forbid_policy(target: str, tool: GovernedTool, param: str, allowed: list[str], gateway_arn: str, what: str) -> str:
    return (
        f"// {tool.name}.{param}: forbid any {what} outside the set (forbid wins)\n"
        f"forbid(\n  principal,\n  action == {action(target, tool.name)},\n"
        f'  resource == AgentCore::Gateway::"{gateway_arn}"\n)\nwhen {{\n'
        f"  context.input has {param} && !({cedar_set(allowed)}.contains(context.input.{param}))\n}};\n"
    )


def generate(kb: KBSet, target: str, tools: list[GovernedTool], gateway_arn: str = GATEWAY_ARN_PLACEHOLDER):
    """Return {file name: cedar text}. One permit file, three forbid files."""
    permits = [permit_policy(target, t, kb, gateway_arn) for t in tools]
    forbids_station, forbids_elevator, forbids_option = [], [], []
    for t in tools:
        for p in t.station_params:
            forbids_station.append(forbid_policy(target, t, p, sorted(kb.stations), gateway_arn, "station"))
        for p in t.elevator_params:
            forbids_elevator.append(forbid_policy(target, t, p, sorted(kb.elevators), gateway_arn, "elevator"))
        for p in t.option_params:
            forbids_option.append(forbid_policy(target, t, p, list(kb.option_labels), gateway_arn, "option label"))
    files = {
        "permit_kb_tools.cedar": HEADER + "\n" + "\n".join(permits),
        "forbid_unknown_station.cedar": HEADER + "\n" + "\n".join(forbids_station),
        "forbid_unknown_elevator.cedar": HEADER + "\n" + "\n".join(forbids_elevator),
        "forbid_unknown_option.cedar": HEADER + "\n" + "\n".join(forbids_option),
    }
    return files


def schema_for(target: str, tools: list[GovernedTool]) -> dict[str, Any]:
    """A Cedar schema in the shape the policy engine auto-generates from the
    gateway's tool definitions: one action per tool, tool parameters as
    optional String attributes under context.input. Policies are validated
    against it locally, the same check AgentCore runs at create_policy time
    with FAIL_ON_ANY_FINDINGS."""
    actions: dict[str, Any] = {}
    for t in tools:
        params = {
            p: {"type": "String", "required": False} for p in t.station_params + t.elevator_params + t.option_params
        }
        actions[f"{target}___{t.name}"] = {
            "appliesTo": {
                "principalTypes": ["OAuthUser", "IamEntity"],
                "resourceTypes": ["Gateway"],
                "context": {
                    "type": "Record",
                    "attributes": {"input": {"type": "Record", "attributes": params, "required": True}},
                },
            }
        }
    return {
        "AgentCore": {
            "entityTypes": {
                "OAuthUser": {"shape": {"type": "Record", "attributes": {}}},
                "IamEntity": {"shape": {"type": "Record", "attributes": {"id": {"type": "String", "required": False}}}},
                "Gateway": {"shape": {"type": "Record", "attributes": {}}},
            },
            "actions": actions,
        }
    }


def validate_locally(policies: str, schema: dict[str, Any]) -> tuple[bool | None, list[str]]:
    """(passed, errors) via cedarpy, or (None, []) when cedarpy is not installed."""
    try:
        from cedarpy import validate_policies
    except ImportError:
        return None, []
    result = validate_policies(policies, schema)
    errors = [str(e) for e in (result.errors or [])] if hasattr(result, "errors") else []
    return bool(result.validation_passed), errors


SCHEMA_FILE = "schema.cedarschema.json"


def write_policies(
    files: dict[str, str], kb: KBSet, target: str, tools: list[GovernedTool], out_dir: Path = POLICY_DIR
) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (out_dir / name).write_text(text)
    schema = schema_for(target, tools)
    (out_dir / SCHEMA_FILE).write_text(json.dumps(schema, indent=2) + "\n")
    passed, errors = validate_locally("\n".join(files.values()), schema)
    manifest: dict[str, Any] = {
        "kb_source": kb.source,
        "kb_frozen_tag": kb.frozen_tag,
        "stations": len(kb.stations),
        "elevators": len(kb.elevators),
        "option_labels": list(kb.option_labels),
        "target_name": target,
        "tools": [t.name for t in tools],
        "files": sorted(files),
        "gateway_arn": GATEWAY_ARN_PLACEHOLDER,
        "validation_mode": "FAIL_ON_ANY_FINDINGS",
        "schema": SCHEMA_FILE,
        "local_validation": "passed"
        if passed
        else ("failed: " + "; ".join(errors) if passed is False else "cedarpy not installed"),
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def request(target: str, tool: str, gateway_arn: str, **inputs: Any) -> dict[str, Any]:
    """An authorization request in cedarpy's shape, for local evaluation."""
    return {
        "principal": 'AgentCore::IamEntity::"arn:aws:sts::000000000000:assumed-role/LastElevatorAgent"',
        "action": action(target, tool),
        "resource": f'AgentCore::Gateway::"{gateway_arn}"',
        "context": {"input": inputs},
    }


def local_decision(policies: str, req: dict[str, Any]) -> str | None:
    """'Allow' | 'Deny' via cedarpy, or None when cedarpy is not installed."""
    try:
        from cedarpy import Decision, is_authorized
    except ImportError:
        return None
    result = is_authorized(req, policies, [])
    return "Allow" if result.decision == Decision.Allow else "Deny"
