"""make cold-start: a stranger's first hour, replayed. The bundle chain is applied into an empty repository, the
tree is archived from the last ref, a fresh virtual environment is created, and the README's setup block is
run line by line as written (`make install`, `make verify`, `make judge`, `make demo-one`); the transcript
of every command with its exit code, timing and last lines goes to docs/reports/cold-start.md.

    python scripts/cold_start.py                # about six minutes; needs the package index for the install
    python scripts/cold_start.py --skip-judge   # verify and demo-one only

The main repo is unreachable from the dispatch session, so "a fresh clone of overnight plus the bundles" is
"an empty repository plus the bundles" here; the laptop runs the same script against its own clone.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT = ROOT / "docs" / "reports" / "cold-start.md"
WORK = ROOT / "build" / "cold-start"


HEADING = "## Setup a stranger could run cold"


def readme_setup_block(readme: Path = ROOT / "README.md") -> list[str]:
    """The commands in the README's setup block, as written; empty when the README has no such block (the
    main repo's own README, until the owner merges the section). The replay reads the archived tree's."""
    text = readme.read_text() if readme.exists() else ""
    if HEADING not in text:
        return []
    section = text[text.index(HEADING) :]
    block = section.split("```")[1]
    commands = []
    for line in block.strip("\n").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            commands.append(line)
    return commands


def sh(cmd: str, cwd: Path, env: dict[str, str] | None = None, timeout: int = 1800) -> tuple[int, str, float]:
    start = time.time()
    out = subprocess.run(cmd, cwd=cwd, shell=True, capture_output=True, text=True, env=env, timeout=timeout)
    return out.returncode, (out.stdout + out.stderr), time.time() - start


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-judge", action="store_true")
    ap.add_argument("--bundles", default=str(ROOT / "build" / "bundles"), help="the bundle folder (make bundles)")
    args = ap.parse_args(argv)
    bundles = Path(args.bundles)
    if not list(bundles.glob("*.bundle")):
        subprocess.run([sys.executable, "scripts/bundles.py", "--out", str(bundles)], cwd=ROOT, check=True)
    if not list(bundles.glob("*.bundle")):  # the main repo: no package history, so no chain to replay
        print("cold-start: no bundles to replay here (the chain is built in the dispatch package, whose CI replays it)")
        return 0
    shutil.rmtree(WORK, ignore_errors=True)
    clone = WORK / "clone"
    tree = WORK / "last-elevator-dispatch"
    clone.mkdir(parents=True)
    tree.mkdir()
    lines = [
        "# Cold start transcript (generated by make cold-start; do not edit)",
        "",
        "An empty repository takes the bundles in INDEX order, the tree is archived from the last ref, a fresh",
        "virtual environment is created, and the README's setup block runs as written. Every command below is",
        "followed by its exit code, its wall time and its last lines. Offline except for the package index.",
        "",
    ]
    subprocess.run(["git", "init", "-q"], cwd=clone, check=True)
    index = (bundles / "INDEX.md").read_text()
    fetches = [line for line in index.splitlines() if line.startswith("git -C ~/agents-for-humans fetch ")]
    last_ref = None
    for line in fetches:
        _, _, _, _, bundle, refspec = line.split()
        code, out, took = sh(f"git fetch -q {bundles / bundle} {refspec}", clone)
        last_ref = refspec.split(":")[1]
        lines += [f"$ git fetch {bundle} {refspec}", f"exit {code}, {took:.1f}s", ""]
        if code:
            lines.append(out)
    assert last_ref, "no fetch lines in INDEX.md"
    archive = subprocess.run(["git", "archive", last_ref], cwd=clone, capture_output=True, check=True)
    subprocess.run(["tar", "-x", "-C", str(tree)], input=archive.stdout, check=True)
    lines += [f"$ git archive {last_ref} | tar -x -C last-elevator-dispatch", "exit 0", ""]
    commands = readme_setup_block(tree / "README.md")  # the archived package's own README, wherever this runs
    assert commands and commands[0].startswith("python3 -m venv .venv"), commands
    failures = 0
    venv_bin = tree / ".venv" / "bin"
    env = {
        "PATH": f"{venv_bin}:{'/usr/bin:/bin:/usr/local/bin'}",
        "HOME": str(WORK),
        "VIRTUAL_ENV": str(tree / ".venv"),
    }
    for proxy in (
        "HTTPS_PROXY",
        "HTTP_PROXY",
        "https_proxy",
        "http_proxy",
        "NO_PROXY",
        "no_proxy",
        "SSL_CERT_FILE",
        "REQUESTS_CA_BUNDLE",
        "PIP_CERT",
    ):
        import os

        if os.environ.get(proxy):
            env[proxy] = os.environ[proxy]
    for cmd in commands:
        if args.skip_judge and cmd.startswith("make judge"):
            lines += [f"$ {cmd}", "skipped (--skip-judge)", ""]
            continue
        code, out, took = sh(cmd, tree, env=env, timeout=2400)
        tail = "\n".join(out.rstrip().splitlines()[-12:])
        tail = re.sub(r"/home/[^ ]*/build/cold-start/", "", tail)
        lines += [f"$ {cmd}", f"exit {code}, {took:.0f}s", "", "```", tail, "```", ""]
        failures += int(code != 0)
        if code and cmd.startswith("python3 -m venv"):
            break
    verdict = "every command exited 0" if not failures else f"{failures} command(s) failed"
    lines += [f"Result: {verdict}.", ""]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines))
    print(f"wrote {REPORT.relative_to(ROOT)}: {verdict}")
    shutil.rmtree(WORK, ignore_errors=True)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
