"""make site: the evidence as a static site a judge can open, built from the documents this package ships.

One page per document (the README, every shipped document under docs/, the evidence packets, the posts, the
video commands, the screenshots index, the reports), the diagrams in place of the Mermaid blocks, the
screenshots as a gallery on the front page, the claims badge, and every `docs/...md` mention turned into a
link. No script, no network, no tracking: HTML and PNG files under build/site/, the same on every run, ready
for GitHub Pages (`.github/workflows/pages.yml` publishes it from main once Pages is switched on in the
repository settings) or for any static host. Nothing here is a result: the pages say what the documents say.

    python scripts/site.py                # build/site/index.html and the rest
    python scripts/site.py --out <dir>    # elsewhere
"""

from __future__ import annotations

import argparse
import html
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = ROOT / "build" / "site"

# the Mermaid blocks that have a rendered picture (make diagrams), by document, in order of appearance
DIAGRAMS = {
    "docs/ARCHITECTURE.md": [
        (
            "diagrams/architecture-poll.png",
            "One poll for one rider: where code decides, where the model proposes, where each gate sits",
        ),
        (
            "diagrams/human-moment.png",
            "The human moment across processes: the pause, the card, the answer, the resumed run",
        ),
    ],
}

CSS = (Path(__file__).with_name("site.css")).read_text()

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title><style>{css}</style></head>
<body><header><a class="brand" href="{up}index.html">Last Elevator</a><nav>{nav}</nav></header>
<main>{body}</main>
<footer>Generated by <code>make site</code> from the documents in the repository; every number on these pages
comes from a results file or is marked pending. Nothing here is a result until the laptop reruns it on the
real knowledge base.</footer></body></html>
"""

NAV = [
    ("readme.html", "README"),
    ("EVIDENCE.html", "Evidence"),
    ("TOUR-TRANSCRIPT.html", "Tour"),
    ("ARCHITECTURE.html", "Architecture"),
    ("THREAT-MODEL.html", "Threat model"),
    ("screenshots.html", "Screenshots"),
    ("devpost.html", "Devpost text"),
]

# what a judge should read first, with one line each (the front page's cards)
FIRST = [
    ("FAQ.html", "The questions a judge asks, each answer pointing at what proves it", "docs/FAQ.md"),
    ("EVIDENCE.html", "Every guarantee with its code, test, span event, results file and claim id", "docs/EVIDENCE.md"),
    (
        "TOUR-TRANSCRIPT.html",
        "What make tour, make ablation, make wire, make demo-runtime and the sweep print",
        "docs/TOUR-TRANSCRIPT.md",
    ),
    (
        "evidence/DELN-E1-daytime.html",
        "One decision as an evidence packet, with its sequence diagram",
        "docs/evidence/DELN-E1-daytime.md",
    ),
    (
        "evidence/DELN-E1-note.html",
        "The rider's own words, read into a fixed vocabulary and applied as feasibility only",
        "docs/evidence/DELN-E1-note.md",
    ),
    (
        "evidence/bedrock-wire.html",
        "The live path offline: every request through the real Bedrock adapter",
        "docs/evidence/bedrock-wire.md",
    ),
    ("ARCHITECTURE.html", "One poll for one rider, and the human moment across processes", "docs/ARCHITECTURE.md"),
    ("THREAT-MODEL.html", "What is trusted, what is not, what stands in", "docs/THREAT-MODEL.md"),
    ("UPSTREAM-NOTE.html", "Five findings about the SDK, each with a reproduction", "docs/UPSTREAM-NOTE.md"),
    (
        "reports/rubric-self-score.html",
        "The rubric, self-scored, with the evidence for every point",
        "docs/reports/rubric-self-score.md",
    ),
]


def pages() -> list[tuple[Path, str]]:
    """(source markdown, output html path relative to the site)."""
    out: list[tuple[Path, str]] = [(ROOT / "README.md", "readme.html")]
    for p in sorted(DOCS.glob("*.md")):
        out.append((p, f"{p.stem}.html"))
    for sub in ("evidence", "posts", "reports"):
        for p in sorted((DOCS / sub).glob("*.md")):
            out.append((p, f"{sub}/{p.stem}.html"))
    out.append((DOCS / "video" / "commands.md", "video/commands.html"))
    out.append((DOCS / "video" / "storyboard.md", "video/storyboard.html"))
    out.append((DOCS / "screenshots" / "README.md", "screenshots.html"))
    return [(p, h) for p, h in out if p.exists()]


def page_for(rel: str, known: dict[str, str]) -> str | None:
    """The site page for a repository path mentioned in a document, if it has one."""
    return known.get(rel.strip("/"))


def prepare(text: str, source: Path, depth: int) -> str:
    """Mermaid blocks to pictures where one exists, images pointed at the site's asset folders."""
    rel = source.relative_to(ROOT).as_posix()
    pictures = list(DIAGRAMS.get(rel, []))
    if rel.startswith("docs/evidence/") and (DOCS / "diagrams" / f"evidence-{source.stem}.png").exists():
        pictures = [
            (
                f"diagrams/evidence-{source.stem}.png",
                "The sequence diagram of this decision: the trip, the gates, the plan",
            )
        ]
    up = "../" * depth

    def swap(match: re.Match) -> str:
        if pictures:
            picture, alt = pictures.pop(0)
            return f"![{alt}]({up}{picture})"
        return "```text\n" + match.group(1) + "```"

    text = re.sub(r"```mermaid\n(.*?)```", swap, text, flags=re.S)
    text = re.sub(r"\]\((?:\.\./)*docs/(diagrams|screenshots|video)/([^)]+\.(?:png|gif))\)", rf"]({up}\1/\2)", text)
    text = re.sub(r"\]\(([0-9]{2}-[a-z-]+\.(?:png|gif))\)", rf"]({up}screenshots/\1)", text)
    return text


def linkify(body: str, known: dict[str, str], depth: int) -> str:
    """`docs/X.md` and `README.md` mentions become links to their pages."""
    up = "../" * depth

    def swap(match: re.Match) -> str:
        target = page_for(match.group(1), known)
        if target:
            return f'<a href="{up}{target}"><code>{match.group(1)}</code></a>'
        return match.group(0)

    return re.sub(r"<code>((?:docs/[A-Za-z0-9_./-]+\.md)|README\.md)</code>", swap, body)


def render_markdown(text: str) -> str:
    import markdown

    return scroll_regions(markdown.markdown(text, extensions=["tables", "fenced_code", "toc"]))


def scroll_regions(body: str) -> str:
    """A region that can scroll sideways (a code block, a wide table) must be reachable from the keyboard,
    or a reader who cannot use a mouse never sees its right-hand side: tabindex on every one (axe's
    scrollable-region-focusable)."""
    body = body.replace("<pre>", '<pre tabindex="0">')
    body = body.replace("<table>", '<div class="scroll" tabindex="0"><table>').replace("</table>", "</table></div>")
    return body


def badge_html() -> str:
    path = ROOT / "results" / "badges" / "claims.json"
    if not path.exists():
        return ""
    badge = json.loads(path.read_text())
    return (
        f'<span class="badge"><span class="l">{html.escape(badge["label"])}</span>'
        f'<span class="v">{html.escape(badge["message"])}</span></span>'
    )


def section(text: str, heading: str) -> str:
    """One `## ` section of a document: from its heading to the next one."""
    start = text.index(heading)
    nxt = text.find("\n## ", start + len(heading))
    return text[start:] if nxt < 0 else text[start : nxt + 1]


def one_screen() -> str:
    """The README's 'In one screen' list and the judges' steps, as they are; in the main repo, whose README
    is its own, the opening of the sections the owner merges (docs/README-sections.md)."""
    readme = ROOT / "README.md"
    text = readme.read_text() if readme.exists() else ""
    if "## In one screen" in text and "## For judges: five minutes" in text:
        screen = section(text, "## In one screen") + "\n" + section(text, "## For judges: five minutes")
        return prepare(screen, readme, 0)
    sections = (DOCS / "README-sections.md").read_text()
    start = sections.index("## Last Elevator")
    end = sections.index("\n### ", start)
    return prepare(sections[start:end], DOCS / "README-sections.md", 0)  # image paths as the site serves them


def first_shot() -> str:
    """The brief's lines from the tour transcript (section 1), as text first, then the picture."""
    transcript = DOCS / "TOUR-TRANSCRIPT.md"
    if not transcript.exists():
        return ""
    text = transcript.read_text()
    start = text.find("== 1. every gate fires")
    if start < 0:
        return ""
    block = text[start:]
    end = block.find("models propose, code decides")
    if end < 0:
        return ""
    lines = block[: end + len("models propose, code decides")].splitlines()[1:]
    lines = [line for line in lines if line.strip()]
    pre = '<pre tabindex="0" class="wrap-lines">' + html.escape("\n".join(lines)) + "</pre>"
    out = "<h2>The first shot: one run, in plain lines</h2>" + pre
    if (DOCS / "screenshots" / "00-first-shot.gif").exists():
        # a reader who asked for reduced motion gets the still; everyone else the lines arriving one per frame
        out += (
            "<p><picture>"
            '<source srcset="screenshots/00-first-shot.png" media="(prefers-reduced-motion: reduce)">'
            '<img src="screenshots/00-first-shot.gif" alt="The same lines arriving one per frame, as make '
            'demo-one-brief prints them"></picture></p>'
        )
    return out


def index_body(known: dict[str, str]) -> str:
    shots = sorted((DOCS / "screenshots").glob("*.png"))
    captions = {}
    index_md = DOCS / "screenshots" / "README.md"
    if index_md.exists():
        for line in index_md.read_text().splitlines():
            if line.startswith("| ") and ".png" in line:
                cells = [c.strip() for c in line.strip("|").split("|")]
                captions[cells[1].strip("`")] = cells[2]
    figures = []
    for p in shots:
        caption = html.escape(captions.get(p.name, p.name))
        figures.append(
            f'<figure><a href="screenshots/{p.name}"><img src="screenshots/{p.name}" alt="{caption}"></a>'
            f"<figcaption>{p.name[:2]} {caption}</figcaption></figure>"
        )
    gallery = "".join(figures)
    cards = "".join(
        f'<div class="card"><a href="{href}">{html.escape(what)}</a><p><code>{src}</code></p></div>'
        for href, what, src in FIRST
    )
    intro = (
        "<h1>Last Elevator: the evidence</h1>"
        "<p>A BART rider who depends on elevators gets warned, rerouted and told what it costs, in the agency's "
        "own words, by an agent whose guarantees are enforced by Strands hooks and steering gates rather than by "
        "prompts, and measured. This site is the package's documents rendered as pages, so a judge can read what "
        "<code>make judge</code> runs. " + badge_html() + "</p>"
        '<p class="note">Fixture run. Every number here comes from a results file the CI checks, and every live '
        "number is marked pending until the laptop reruns it on the real knowledge base and a live model.</p>"
    )
    body = intro + first_shot() + linkify(render_markdown(one_screen()), known, 0)
    body += '<h2>Read first</h2><div class="cards">' + cards + "</div>"
    body += '<h2>Screenshots</h2><div class="gallery">' + gallery + "</div>"
    body += (
        "<h2>Every page</h2><ul>"
        + "".join(
            f'<li><a href="{h}">{html.escape(h)}</a> <code>{html.escape(p.relative_to(ROOT).as_posix())}</code></li>'
            for p, h in pages()
        )
        + "</ul>"
    )
    return body


def build(out: Path) -> list[Path]:
    shutil.rmtree(out, ignore_errors=True)
    out.mkdir(parents=True)
    for folder in ("diagrams", "screenshots", "video"):
        src = DOCS / folder
        if src.exists():
            (out / folder).mkdir(exist_ok=True)
            for p in list(src.glob("*.png")) + list(src.glob("*.gif")):
                shutil.copy(p, out / folder / p.name)
    known = {p.relative_to(ROOT).as_posix(): h for p, h in pages()}
    nav_items = [(h, label) for h, label in NAV if h in known.values()]  # no README page in the main repo
    written = []
    for source, href in pages():
        depth = href.count("/")
        up = "../" * depth
        text = prepare(source.read_text(), source, depth)
        body = linkify(render_markdown(text), known, depth)
        nav = " ".join(f'<a href="{up}{h}">{label}</a>' for h, label in nav_items)
        title = next((line.lstrip("# ").strip() for line in text.splitlines() if line.startswith("# ")), source.stem)
        page = PAGE.format(title=html.escape(f"{title} | Last Elevator"), css=CSS, nav=nav, body=body, up=up)
        target = out / href
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(page)
        written.append(target)
    nav = " ".join(f'<a href="{h}">{label}</a>' for h, label in nav_items)
    (out / "index.html").write_text(
        PAGE.format(title="Last Elevator: the evidence", css=CSS, nav=nav, body=index_body(known), up="")
    )
    (out / ".nojekyll").write_text("")
    return [out / "index.html", *written]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args(argv)
    try:
        import markdown  # noqa: F401
    except ImportError:
        print("site: the markdown package is not installed (pip install -e '.[dev]'); skipped")
        return 0
    written = build(Path(args.out))
    print(f"wrote {len(written)} pages under {Path(args.out)} (open index.html)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
